#!/bin/bash
# simple push command
echo "cleaning up"
set +x
#
#
#git remote set-url origin git@github.com:airflow/air.git
echo +x
echo "pushing to GitHub changes including $1"
echo -x
git add .
git commit -vm "$1"
git push origin master
